name: dima
description: "DIMA"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  cloud_firestore:
  firebase_auth: ^4.4.0
  firebase_storage: ^11.7.6
  image_picker: ^1.1.2
  path_provider: ^2.0.14
  path: ^1.9.0
  google_sign_in: ^6.2.1
  flip_card: ^0.5.0
  flutter_swiper_null_safety: ^1.0.2
  google_maps_flutter:
  flutter_polyline_points: ^1.0.0
  algolia:
  shimmer: ^2.0.0
  provider: ^6.0.1
  font_awesome_flutter: ^10.7.0
  geolocator:
  url_launcher: ^6.0.20
  badges: ^3.1.2
  intl: ^0.17.0
  palette_generator:
  flutter_launcher_icons: ^0.9.2
  sign_in_with_apple: ^6.1.1
  firebase_auth_mocks: ^0.9.2
  google_sign_in_mocks: ^0.3.0
  flutter_screenutil: ^5.0.0
  network_image_mock: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito:
  build_runner:

dependency_overrides:
#firebase_core_platform_interface: 4.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
